export const PRODUCTS = [
  {
    id: 1,
    name: "Nike Mercurial Vapor 15",
    price: 899.90,
    category: "Campo",
    image: "/mercurial.png",
    description: "A chuteira mais rápida da Nike, projetada para velocidade e tração explosiva.",
    sizes: [38, 39, 40, 41, 42, 43],
    colors: ["Neon", "Black"],
  },
  {
    id: 2,
    name: "Adidas Predator Accuracy",
    price: 750.00,
    category: "Society",
    image: "/predator.png",
    description: "Controle absoluto e precisão extrema para os mestres do meio-campo.",
    sizes: [39, 40, 41, 42, 44],
    colors: ["Blue", "White"],
  },
  {
    id: 3,
    name: "Nike React Phantom GX",
    price: 920.00,
    category: "Futsal",
    image: "/phantom.png",
    description: "Tecnologia de toque preciso para jogadores técnicos em quadras de salão.",
    sizes: [37, 38, 39, 40, 41],
    colors: ["Volt", "Black"],
  },
  {
    id: 4,
    name: "Puma Future Ultimate",
    price: 849.00,
    category: "Campo",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800",
    description: "Agilidade redefinida com ajuste adaptável para movimentos dinâmicos.",
    sizes: [40, 41, 42, 43],
    colors: ["Orange", "Blue"],
  },
  {
    id: 5,
    name: "Mizuno Morelia Neo IV",
    price: 1200.00,
    category: "Campo",
    image: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&q=80&w=800",
    description: "O auge do conforto e durabilidade com couro de canguru premium.",
    sizes: [38, 40, 41, 42],
    colors: ["White", "Gold"],
  },
  {
    id: 6,
    name: "Adidas Telstar Classic",
    price: 450.00,
    category: "Society",
    image: "https://images.unsplash.com/photo-1511886929837-354d827aae26?auto=format&fit=crop&q=80&w=800",
    description: "Um clássico que nunca sai de moda, agora com amortecimento moderno.",
    sizes: [39, 40, 41, 42, 43],
    colors: ["Black", "White"],
  }
];
